spring:
  application:
    name: portfolio-service
  datasource:
    url: jdbc:postgresql://localhost:5432/trading-platform
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest


server:
  port: 8084


kafka:
  topic:
    position-updates: position-update
    position-events: position-event
    order-events: order-events


logging:
  level:
    org.springframework: INFO
